### ISSUE TITLE
Import  { init } from 'buttercup' fails "expected to be CommonJS"

### ISSUE THREAD

**Issue by cullub** [buttercup/buttercup-core#286]
I'm getting the following error:

```
file:///C:/Users/cullub/Desktop/myproject/myFile.js:1
import { Credentials, FileDatasource, Vault, init } from 'buttercup';
                                             ^^^^
SyntaxError: The requested module 'buttercup' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'buttercup';
const { Credentials, FileDatasource, Vault, init } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:162:24)
```

However, that line is taken directly from the buttercup-core README.md.  Maybe your package.json is missing a `type: module`?

**Comment by cullub** [comment]
Maybe related: https://github.com/nodejs/node/issues/32137

**Comment by HomemadeToast57** [comment]
Hey! It is 2 years later now. Due to the broad support of ES modules in Node in 2022, would you have any interest in forming a combined effort to update this project to support them. I would love to be part of this and would be happy to contribute! :) Lmk!
